config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :customers, only:[:index,:update,:edit]
  end
 root to:"homes#top"
  get "home/about" =>"home#about"
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }
  
  namespace :admin do
   resources :game_titles
   get "search" => "searches#search"
   get "search/result"=>"searches#search_result"
   resources :reviews,only:[:edit,:update,:destroy,:index]
   resources :requests,only:[:index,:destroy]
   get "resolved" => 'reviews#resolved' 
   get 'unsolved' => 'reviews#unsolved'
  end
  
  scope module: :public do 
    resources :customers,only:[:edit,:update,:index,:show] do
    resources :favorites,only:[:index]
    resources :relationships, only: [:create, :destroy,:index]
    get 'followings' => 'relationships#followings',as: 'followings'
    get 'followers' => 'relationships#followers',as: 'followers'
    end
    resources :requests, only: [:new,:create]
    resources :reviews,except:[:edit,:update]
    get "lowrating" => 'reviews#lowrating' 
    get 'highrating' => 'reviews#highrating'
    get "search" => "searches#search"
    get "search/result" => "searches#search_result"
    
    
    # 退会確認画面
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
    resources :game_titles do
     resources :game_scores,only:[:index,:show,:create]
    end
    resources :game_scores do
     resources :reasons,except:[:index]
     
     resource :favorites,only:[:create,:destroy,:index]
    get "/reasons/new/lose" =>"reasons#lose" ,as: "lose_reason"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reviews, dependent: :destroy
    
    #フォローした、されたの関係
    has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
    has_many :reverse_of_relationships,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
    
    #一覧画面で使う
    has_many :followings,through: :relationships, source: :followed
    has_many :followers,through: :reverse_of_relationships, source: :follower
         
    has_many :game_scores
    has_many :favorites ,dependent: :destroy
    
    validates :name, presence: true, uniqueness: true,length: { in: 1..15 }
    validates :profile ,length: {maximum: 50 }
    has_one_attached :customer_image
    
    def get_customer_image(width,height)
      unless customer_image.attached?
        file_path = Rails.root.join('app/assets/images/noimage.png')
        customer_image.attach(io: File.open(file_path), filename: 'default-image.png',content_type: 'image/png')
      end
      customer_image.variant(resize_to_fill: [width,height]).processed
    end
    
    def self.looks(word)
        @customer = Customer.where("name LIKE?","%#{word}%")
    end

    def active_for_authentication?
      super && (is_deleted == false)
    end
    
    def follow(customer_id)
      relationships.create(followed_id: customer_id)
    end
    
    # フォローを外す処理
    def unfollow(customer_id)
      relationships.find_by(followed_id: customer_id).destroy
    end
    
    def following?(customer)
      followings.include?(customer)
    end
    
    def guest_user?
      self.name=="guest_user"
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :game_score
end

app/models/game_score.rb
class GameScore < ApplicationRecord
  belongs_to :game_title
  belongs_to :customer
  has_many :reasons,dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  
  def winrate
    if self.reasons.where(status: "win").count==0
     '0'
    else
    self.reasons.where(status: "win").count*100/self.reasons.count
    end
  end
  
 
end

app/models/game_title.rb
class GameTitle < ApplicationRecord
  has_one_attached :image
  has_many :game_scores ,dependent: :destroy
  validates :image, presence: true
  
  def get_game_title_image
      image.variant(resize_to_fill: [200, 200]).processed
  end
  
  def self.looks(word)
    @game_titles = GameTitle.where("title LIKE?","%#{word}%")
  end
end

app/models/reason.rb
class Reason < ApplicationRecord
  enum status: { win: 0, lose: 1 }
  belongs_to :game_score
validates :title ,length: {minimum:1 ,maximum: 20 },presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
  
  
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @reviews = Review.all.page(params[:page]).per(10)
  end
  
  def edit
    @review = Review.find(params[:id])
  end
  
  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to admin_reviews_path
  end
  # 未確認質問
  def resolved
    @reviews = Review.where(is_settled: 1).page(params[:page]).per(10)
  end
  
  # 確認済み質問
  def unsolved
    @reviews = Review.where(is_settled: 0).page(params[:page]).per(10)
  end

  def destroy 
    review = Review.find(params[:id])
    review.destroy
    redirect_to admin_reviews_path
  end
  
  private
  def review_params
    params.require(:review).permit(:customer_id,:title,:body,:is_settled)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
  # def  after_sign_in_path_for(resource)
  #   case resource
  #     when Customer
  #       game_titles_path
  #     when Admin
  #       admin_game_titles_path
  #   end
  # end
   
   protected

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @customer = Customer.find_by(name: params[:user][:name])
    if @customer
      if @customer.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def guest_sign_in
    customer = Customer.find_or_create_by!(name: 'guest_user',email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
    sign_in customer
    redirect_to game_titles_path, notice: "ゲストとしてログインしました"
  end
  
  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/requsts_helper.rb
module RequstsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto mt-2">
      <%= form_with model: @review,url: admin_review_path(@review),method: :patch  do |f| %>
        <div class="row mx-auto">
          <div class="col-md-4 col-sm-4 mt-4">タイトル</div>
          <div class="col-md-6 col-sm-8 mt-4"><%= f.text_field :title, placeholder:"タイトルを入力してください",class:"form-control" %></div>
        </div>
          
        <div class="row mx-auto">
          <div class="col-md-4 col-sm-4 mt-4">レビュー</div>
          <div class="col-md-6 col-sm-8 mt-4"><%= f.text_area :body, placeholder:"レビューを入力してください",class:"form-control" %></div>
        </div>
        
        <div class="row mx-auto">
          <div class="col-md-4 col-sm-4 mt-4">確認ステータス</div>
          <div class="col-md-6 col-sm-8 mt-4">
            <%= f.radio_button :is_settled, :false %><%= f.label :is_settled_false,"未確認" %>
            <%= f.radio_button :is_settled, :true %><%= f.label :is_settled_true,"確認済み" %>
          </div>
        </div>
          
        <div class="row mx-auto">
          <div class="col-md-4 col-sm-4 mt-4"></div>
          <div class="col-md-6 col-sm-8 mt-4"><%= f.submit "更新する" ,class:"btn btn-success"%></div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 col-sm-12 mx-auto">
      <div class="row">
          <div class="col-12 review_btn text-center my-3"><%= link_to "リクエスト一覧を見る",admin_requests_path,class:"text-white text-decoration-none"%></div>
        </div>
      <div class="row">
        <div class="col-3 review_btn text-center mx-auto bg-dark"><%= link_to "全てのレビュー",admin_reviews_path,class:"text-white text-decoration-none" %></div>
        <div class="col-4 review_btn text-center text-white mx-auto"><%= link_to "未確認のレビュー",admin_unsolved_path,class:"text-white text-decoration-none"  %></div>
        <div class="col-4 review_btn text-center text-white mx-auto"><%= link_to "確認済みのレビュー",admin_resolved_path,class:"text-white text-decoration-none"  %></div>
      </div>
      <% @reviews.each do |review| %>
        <%= link_to edit_admin_review_path(review) do %>
          <div class="border mx-auto py-2 my-4 px-3">
            <div class="row">
              <div class="col-2">
                <%= image_tag review.customer.get_customer_image(50,50),class:"rounded-circle" %>
              </div>
              <div class="col-7"> 
                <%=review.customer.name %><br><span class="font-weight-bold"><%= review.title%></span><br><%=review.created_at.strftime('%Y/%m/%d %H:%M') %><br><%= review.body %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
       <div class="row col-12 text-center d-flex justify-content-center">
        <div class="col-8 col-sm-12 my-4"><%= paginate @reviews ,theme: 'bootstrap-5'%></div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/resolved.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 col-sm-12 mx-auto">
      <div class="row">
        <div class="col-3 review_btn text-center mx-auto "><%= link_to "全てのレビュー",admin_reviews_path,class:"text-white text-decoration-none" %></div>
        <div class="col-4 review_btn text-center text-white mx-auto"><%= link_to "未確認のレビュー",admin_unsolved_path,class:"text-white text-decoration-none"  %></div>
        <div class="col-4 review_btn text-center text-white mx-auto bg-dark"><%= link_to "確認済みのレビュー",admin_resolved_path,class:"text-white text-decoration-none"  %></div>
      </div>
      <% @reviews.each do |review| %>
        <%= link_to edit_admin_review_path(review) do %>
          <div class="border mx-auto py-2 my-4 px-3">
            <div class="row">
              <div class="col-2">
                <%= image_tag review.customer.get_customer_image(50,50),class:"rounded-circle" %>
              </div>
              <div class="col-7"> 
                <%=review.customer.name %><br><span class="font-weight-bold"><%= review.title%></span><br><%=review.created_at.strftime('%Y/%m/%d %H:%M') %><br><%= review.body %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
       <div class="row col-12 text-center d-flex justify-content-center">
        <div class="col-8 col-sm-12 my-4"><%= paginate @reviews ,theme: 'bootstrap-5'%></div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/unsolved.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 col-sm-12 mx-auto">
      <div class="row">
        <div class="col-3 review_btn text-center mx-auto "><%= link_to "全てのレビュー",admin_reviews_path,class:"text-white text-decoration-none" %></div>
        <div class="col-4 review_btn text-center text-white mx-auto bg-dark"><%= link_to "未確認のレビュー",admin_unsolved_path,class:"text-white text-decoration-none"  %></div>
        <div class="col-4 review_btn text-center text-white mx-auto"><%= link_to "確認済みのレビュー",admin_resolved_path,class:"text-white text-decoration-none"  %></div>
      </div>
      <% @reviews.each do |review| %>
        <%= link_to edit_admin_review_path(review) do %>
          <div class="border mx-auto py-2 my-4 px-3">
            <div class="row">
              <div class="col-2">
                <%= image_tag review.customer.get_customer_image(50,50),class:"rounded-circle" %>
              </div>
              <div class="col-7"> 
                <%=review.customer.name %><br><span class="font-weight-bold"><%= review.title%></span><br><%=review.created_at.strftime('%Y/%m/%d %H:%M') %><br><%= review.body %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
       <div class="row col-12 text-center d-flex justify-content-center">
        <div class="col-8 col-sm-12 my-4"><%= paginate @reviews ,theme: 'bootstrap-5'%></div>
      </div>
    </div>
  </div>
</div>