config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :customers, only:[:index,:update,:edit]
  end
 root to:"homes#top"
  get "home/about" =>"home#about"
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords],controllers: {
      sessions: "admin/sessions"
  }
  
  namespace :admin do
   resources :game_titles
   get "search" => "searches#search"
   get "search/result"=>"searches#search_result"
   resources :reviews,only:[:edit,:update,:destroy,:index]
   resources :requests,only:[:index,:destroy]
   get "resolved" => 'reviews#resolved' 
   get 'unsolved' => 'reviews#unsolved'
  end
  
  scope module: :public do 
    resources :customers,only:[:edit,:update,:index,:show] do
    resources :favorites,only:[:index]
    resources :relationships, only: [:create, :destroy,:index]
    get 'followings' => 'relationships#followings',as: 'followings'
    get 'followers' => 'relationships#followers',as: 'followers'
    end
    resources :requests, only: [:new,:create]
    resources :reviews,except:[:edit,:update]
    get "lowrating" => 'reviews#lowrating' 
    get 'highrating' => 'reviews#highrating'
    get "search" => "searches#search"
    get "search/result" => "searches#search_result"
    
    
    # 退会確認画面
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
    resources :game_titles do
     resources :game_scores,only:[:index,:show,:create]
    end
    resources :game_scores do
     resources :reasons,except:[:index]
     
     resource :favorites,only:[:create,:destroy,:index]
    get "/reasons/new/lose" =>"reasons#lose" ,as: "lose_reason"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reviews, dependent: :destroy
    
    #フォローした、されたの関係
    has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
    has_many :reverse_of_relationships,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
    
    #一覧画面で使う
    has_many :followings,through: :relationships, source: :followed
    has_many :followers,through: :reverse_of_relationships, source: :follower
         
    has_many :game_scores
    has_many :favorites ,dependent: :destroy
    
    validates :name, presence: true, uniqueness: true,length: { in: 1..15 }
    validates :profile ,length: {maximum: 50 }
    has_one_attached :customer_image
    
    def get_customer_image(width,height)
      unless customer_image.attached?
        file_path = Rails.root.join('app/assets/images/noimage.png')
        customer_image.attach(io: File.open(file_path), filename: 'default-image.png',content_type: 'image/png')
      end
      customer_image.variant(resize_to_fill: [width,height]).processed
    end
    
    def self.looks(word)
        @customer = Customer.where("name LIKE?","%#{word}%")
    end

    def active_for_authentication?
      super && (is_deleted == false)
    end
    
    def follow(customer_id)
      relationships.create(followed_id: customer_id)
    end
    
    # フォローを外す処理
    def unfollow(customer_id)
      relationships.find_by(followed_id: customer_id).destroy
    end
    
    def following?(customer)
      followings.include?(customer)
    end
    
    def guest_user?
      self.name=="guest_user"
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :game_score
end

app/models/game_score.rb
class GameScore < ApplicationRecord
  belongs_to :game_title
  belongs_to :customer
  has_many :reasons,dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  
  def winrate
    if self.reasons.where(status: "win").count==0
     '0'
    else
    self.reasons.where(status: "win").count*100/self.reasons.count
    end
  end
  
 
end

app/models/game_title.rb
class GameTitle < ApplicationRecord
  has_one_attached :image
  has_many :game_scores ,dependent: :destroy
  validates :image, presence: true
  
  def get_game_title_image
      image.variant(resize_to_fill: [200, 200]).processed
  end
  
  def self.looks(word)
    @game_titles = GameTitle.where("title LIKE?","%#{word}%")
  end
end

app/models/reason.rb
class Reason < ApplicationRecord
  enum status: { win: 0, lose: 1 }
  belongs_to :game_score
validates :title ,length: {minimum:1 ,maximum: 20 },presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
  
  
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
  # def  after_sign_in_path_for(resource)
  #   case resource
  #     when Customer
  #       game_titles_path
  #     when Admin
  #       admin_game_titles_path
  #   end
  # end
   
   protected

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @customer = Customer.find_by(name: params[:user][:name])
    if @customer
      if @customer.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def guest_sign_in
    customer = Customer.find_or_create_by!(name: 'guest_user',email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
    sign_in customer
    redirect_to game_titles_path, notice: "ゲストとしてログインしました"
  end
  
  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/requsts_helper.rb
module RequstsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoughRoad</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://kit.fontawesome.com/2b47545f71.js" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="crossorigin="anonymous">
     </script>
    <%= favicon_link_tag 'favicon-cat.ico' %>
  </head>

  <body>
<!--ここからヘッダー-->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">

     <a class="navbar-brand" href="/">
      <%= image_tag 'Rough.png',class: "logo-image", width: "150", height: "90" %>
     </a>
    
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
     <% if admin_signed_in? %>
       <%= render "admin/searches/searches" %>
     <% elsif customer_signed_in? %>
       <%= render "public/searches/searches" %>
     <% else %>
     <% end %>
     
     
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       
<!--－管理者ログインの場合-->
     <% if admin_signed_in? %>
       <ul class="navbar-nav ml-auto">
         <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "mx-2 my-1 btn btn-secondary" %></li>
         <li class="nav-item"><%= link_to "タイトル追加", new_admin_game_title_path, class: "mx-2 my-1 btn btn-secondary" %></li>
         <li class="nav-item"><%= link_to "タイトル一覧", admin_game_titles_path, class: "mx-2 my-1 btn btn-secondary" %></li>
         <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "mx-2  my-1 btn btn-secondary" %></li>
         <li class="nav-item"><%= link_to "レビュー", admin_reviews_path, class: "mx-2  my-1 btn btn-secondary" %></li>
       </ul>
       
<!--ユーザーログインの場合-->
     <% elsif customer_signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "マイページ", customer_path(current_customer.id), class: "mx-2 my-1 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "タイトル一覧", game_titles_path, class: "mx-2 my-1 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "お気に入り", customer_favorites_path(current_customer), class: "mx-2 my-1 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "mx-2  my-1 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "レビュー", reviews_path, class: "mx-2  my-1 btn btn-secondary" %></li>
      </ul>
    
<!--ログインしていない場合-->
      <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "ゲストログイン", homes_guest_sign_in_path,method: :post, class: "mx-3 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "mx-3 btn btn-secondary" %></li>
        <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "mx-3 btn btn-secondary" %></li>
      </ul>
    
     <% end %>
      </div>
    </nav>
  </header>
  
<!--ここからメイン-->
  <main>
    <% if flash[:notice].present? || flash[:alert].present? %>
      <div class="text-success"><h5><%=flash[:notice] %></h5></div>
      <div class="text-danger"><h5><%=flash[:alert] %></h5></div>
    <% end %>
    <%= yield %>
  </main>
  </body>
</html>

app/views/layouts/nemoheader.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

<a class="navbar-brand" href="/">

<%= image_tag "logo.png", class: "logo-image", width: "150", height: "auto" %>

</a>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

<span class="navbar-toggler-icon"></span>

</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">

<% if member_signed_in? %>

<ul class="navbar-nav ml-auto">

<li class="nav-item"><%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "mx-3 text-white" %></li>

<li class="nav-item"><%= link_to "マイページ", member_path(current_member.id), class: "mx-3 text-white" %></li>

<li class="nav-item"><%= link_to "コミュニティへ", categories_path, class: "mx-3 text-white" %></li>

<li class="nav-item"><%= link_to "新規投稿", new_post_path, class: "mx-3 text-white" %></li>

</ul>

<% else %>

<ul class="navbar-nav ml-auto">

<li class="nav-item"><%= link_to "ログイン", new_member_session_path, class: "mx-3 text-white" %></li>

<li class="nav-item"><%= link_to "新規登録", new_member_registration_path, class: "mx-3 text-white" %></li>

<li class="nav-item"><%= link_to "アプリについて", home_about_path, class: "mx-3 text-white" %></li>

</ul>

<% end %>

</div>

</nav>